### ISSUE TITLE
Alias for different ingredients

### ISSUE THREAD

**Issue by umgefahren** [cooklang/spec#5] opened 2021-10-26 15:39 UTC
Consider a recipe that requires waxy potatoes and floury potatoes. Some sort of alias would be great.
This could improve the readability.

**Comment by dubadub** [comment] 2021-11-11 07:50
Hi @umgefahren, I'm not 100% confident that I understand what you mean. 

Let's imagine we have a recipe with both waxy potatoes and floury potatoes. What you're saying is that we will give short names for them and use the short names instead? If possible could you please give an example?

**Comment by dubadub** [comment] 2022-01-05 19:24
Closing as duplicate of https://github.com/cooklang/spec/issues/47

**Closed by dubadub** 2022-01-05 19:24 UTC
